### ISSUE TITLE
How to show the jira data in Hygieia UI?

### ISSUE THREAD

**Issue by Hemila-S** [Hygieia/hygieia-feature-jira-collector#27]
Hi , 
Am new to this Hygieia!
My issue is am not able to fetch the data present in JIRA

2019-12-03 10:36:00,134 [taskScheduler-1] INFO  c.c.d.collector.FeatureCollectorTask - JIRA Collector is set to work in Team mode
2019-12-03 10:36:00,135 [taskScheduler-1] INFO  c.c.d.collector.FeatureCollectorTask - Hours since last run = 4. Collector is only collecting updated/new issues.
2019-12-03 10:36:00,138 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Finished                         0s

Can anyone guide me how to show the data in UI dashboard
Any help please!

**Comment by Sbrenthughes** [comment]
Can you post your properties file

**Comment by Hemila-S** [comment]
Sure

**Comment by Hemila-S** [comment]
server.contextPath=/api
server.port=8080

# Database Name
dbname=dashboarddb

# Database HostName - default is localhost
dbhost=localhost

# Database Port - default is 27017
dbport=27017

# MongoDB replicaset
dbreplicaset=false
dbhostport=localhost:27017

# Database Username - default is blank
dbusername=dashboarduser

# Database Password - default is blank
dbpassword=dbpassword

# Logging File location
logging.file=./logs/jira.log

# PageSize - Expand contract this value depending on Jira implementation's
# default server timeout setting (You will likely receive a SocketTimeoutException)
feature.pageSize=100

# Delta change date that modulates the collector item task
# Occasionally, these values should be modified if database size is a concern
feature.deltaStartDate=2016-03-01T00:00:00.000000
feature.masterStartDate=2016-03-01T00:00:00.000000
feature.deltaCollectorItemStartDate=2016-03-01T00:00:00.000000

# Chron schedule: S M D M Y [Day of the Week]
feature.cron=0 0/1 * * * *

# ST Query File Details - Required, but DO NOT MODIFY
feature.queryFolder=jiraapi-queries
feature.storyQuery=Story
feature.epicQuery=Epic


# JIRA CONNECTION DETAILS:
# Enterprise Proxy - ONLY INCLUDE IF YOU HAVE A PROXY
; feature.jiraProxyUrl=http://proxy.com
; feature.jiraProxyPort=9000

feature.jiraBaseUrl=https://parkercfa.atlassian.net/
feature.jiraQueryEndpoint=rest/api/2/
# For basic authentication, requires username:password as string in base64
# This command will make this for you:  echo -n username:password | base64

;feature.jiraCredentials=dmVua2F0ZXNoLmduYW5hc2VrYXJhbkBwYXJrZXIuY29tOkd1cnVjaGVsbGFtQDc=
;feature.jiraCredentials=venkatesh.gnanasekaran@parker.com:Guruchellam@7

# OAuth is not fully implemented; please blank-out the OAuth values:

; feature.jiraOauthAuthtoken=
; feature.jiraOauthRefreshtoken=
; feature.jiraOauthRedirecturi=
; feature.jiraOauthExpiretime=

#############################################################################
# In Jira, general IssueType IDs are associated to various 'issue'
# attributes. However, there is one attribute which this collector's
# queries rely on that change between different instantiations of Jira.
# Please provide a string name reference to your instance's IssueType for
# the lowest level of Issues (for example, 'user story') specific to your Jira
# instance.  Note:  You can retrieve your instance's IssueType Name
# listings via the following URI:  https://[your-jira-domain-name]/rest/api/2/issuetype/
# Multiple comma-separated values can be specified.
#############################################################################
feature.jiraIssueTypeNames=Story

#############################################################################
# In Jira, your instance will have its own custom field created for 'sprint' or 'timebox' details,
# which includes a list of information.  This field allows you to specify that data field for your
# instance of Jira. Note: You can retrieve your instance's sprint data field name
# via the following URI, and look for a package name com.atlassian.greenhopper.service.sprint.Sprint;
# your custom field name describes the values in this field:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
;feature.jiraSprintDataFieldName=customfield_10005
feature.jiraSprintDataFieldName=customfield_10000

#############################################################################
# In Jira, your instance will have its own custom field created for 'super story' or 'epic' back-end ID,
# which includes a list of information.  This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's epic ID field name via the following URI where your
# queried user story issue has a super issue (for example, epic) tied to it; your custom field name describes the
# epic value you expect to see, and is the only field that does this for a given issue:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
;feature.jiraEpicIdFieldName=customfield_10307
feature.jiraEpicIdFieldName=customfield_10002

#############################################################################
# In Jira, your instance will have its own custom field created for 'story points'
# This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's storypoints ID field name via the following URI where your
# queried user story issue has story points set on it; your custom field name describes the
# story points value you expect to see:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
;feature.jiraStoryPointsFieldName=customfield_10300

;feature. jiraStoryIds[0]=customfield_10300

feature.jiraStoryPointsFieldName=customfield_10003

#############################################################################
# In Jira, your instance will have its own custom field created for 'team'
# This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's team ID field name via the following URI where your
# queried user story issue has team set on it; your custom field name describes the
# team value you expect to see:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraTeamFieldName= 
feature.maxNumberOfFeaturesPerBoard=1000

# Defines how to update features per board. If true then only update based on enabled collectorItems otherwise full update
feature.collectorItemOnlyUpdate=true

#Defines the maximum number of features allow per board. If limit is reach collection will not happen for given board
feature.maxNumberOfFeaturesPerBoard=8000

# Set this to true if you use boards as team
;feature.jiraBoardAsTeam=true
feature.jiraBoardAsTeam=false
#Defines the number of hours between each board/team and project data refresh
feature.refreshTeamAndProjectHours=3
;feature.refreshTeamAndProjectHours=4

**Comment by Hemila-S** [comment]
We have made the changes in the application.properties file which is present in this path "D:\_Hygieia\api\src\main\resources"

**Comment by Sbrenthughes** [comment]
Why do you have `;` in your properties file? I have not seen this before

**Comment by Hemila-S** [comment]
That is commented lines

**Comment by Hemila-S** [comment]
server.contextPath=/api
server.port=8080

# Database Name
dbname=dashboarddb

# Database HostName - default is localhost
dbhost=localhost

# Database Port - default is 27017
dbport=27017

# MongoDB replicaset
# modified
dbreplicaset=true
dbhostport=localhost:27017

# Database Username - default is blank
dbusername=dashboarduser

# Database Password - default is blank
dbpassword=dbpassword

# Logging File location
logging.file=./logs/jira.log

# PageSize - Expand contract this value depending on Jira implementation's
# default server timeout setting (You will likely receive a SocketTimeoutException)
feature.pageSize=100

# Delta change date that modulates the collector item task
# Occasionally, these values should be modified if database size is a concern
feature.deltaStartDate=2016-03-01T00:00:00.000000
feature.masterStartDate=2016-03-01T00:00:00.000000
feature.deltaCollectorItemStartDate=2016-03-01T00:00:00.000000

# Chron schedule: S M D M Y [Day of the Week]
feature.cron=0 0/1 * * * *

# ST Query File Details - Required, but DO NOT MODIFY
feature.queryFolder=jiraapi-queries
feature.storyQuery=Story
feature.epicQuery=Epic


# JIRA CONNECTION DETAILS:
# Enterprise Proxy - ONLY INCLUDE IF YOU HAVE A PROXY
# feature.jiraProxyUrl=http://proxy.com
# feature.jiraProxyPort=9000

feature.jiraBaseUrl=https://parkercfa.atlassian.net/
feature.jiraQueryEndpoint=rest/api/2/
# For basic authentication, requires username:password as string in base64
# This command will make this for you:  echo -n username:password | base64

# OAuth is not fully implemented; please blank-out the OAuth values:

# feature.jiraOauthAuthtoken=
# feature.jiraOauthRefreshtoken=
# feature.jiraOauthRedirecturi=
#feature.jiraOauthExpiretime=

#############################################################################
# In Jira, general IssueType IDs are associated to various 'issue'
# attributes. However, there is one attribute which this collector's
# queries rely on that change between different instantiations of Jira.
# Please provide a string name reference to your instance's IssueType for
# the lowest level of Issues (for example, 'user story') specific to your Jira
# instance.  Note:  You can retrieve your instance's IssueType Name
# listings via the following URI:  https://[your-jira-domain-name]/rest/api/2/issuetype/
# Multiple comma-separated values can be specified.
#############################################################################
feature.jiraIssueTypeNames= Story,Epic

#############################################################################
# In Jira, your instance will have its own custom field created for 'sprint' or 'timebox' details,
# which includes a list of information.  This field allows you to specify that data field for your
# instance of Jira. Note: You can retrieve your instance's sprint data field name
# via the following URI, and look for a package name com.atlassian.greenhopper.service.sprint.Sprint;
# your custom field name describes the values in this field:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraSprintDataFieldName=customfield_10005


#############################################################################
# In Jira, your instance will have its own custom field created for 'super story' or 'epic' back-end ID,
# which includes a list of information.  This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's epic ID field name via the following URI where your
# queried user story issue has a super issue (for example, epic) tied to it; your custom field name describes the
# epic value you expect to see, and is the only field that does this for a given issue:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraEpicIdFieldName=customfield_10005
#feature.jiraEpicIdFieldName=customfield_10002

#############################################################################
# In Jira, your instance will have its own custom field created for 'story points'
# This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's storypoints ID field name via the following URI where your
# queried user story issue has story points set on it; your custom field name describes the
# story points value you expect to see:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraStoryPointsFieldName=customfield_10003

#feature. jiraStoryIds[0]=customfield_10300


#############################################################################
# In Jira, your instance will have its own custom field created for 'team'
# This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's team ID field name via the following URI where your
# queried user story issue has team set on it; your custom field name describes the
# team value you expect to see:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
#feature.jiraTeamFieldName=customfield_10001

feature.maxNumberOfFeaturesPerBoard=1000

# Defines how to update features per board. If true then only update based on enabled collectorItems otherwise full update
feature.collectorItemOnlyUpdate=true

#Defines the maximum number of features allow per board. If limit is reach collection will not happen for given board
feature.maxNumberOfFeaturesPerBoard=8000

# Set this to true if you use boards as team
feature.jiraBoardAsTeam=true

#Defines the number of hours between each board/team and project data refreshfeature.refreshTeamAndProjectHours=3
feature.refreshTeamAndProjectHours=4

**Comment by Hemila-S** [comment]
Above comment is the updated properties file .,we are getting the below output in cmd prompt
-------------------------------------------
2019-12-06 03:16:00,003 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2019-12-06 03:16:00,614 [taskScheduler-1] INFO  c.c.dashboard.client.RestClient - makeRestCall op=GET url=https://parkercfa.atlassian.net/rest/api/2/issuetype status=200 duration=577
2019-12-06 03:16:00,678 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-12-06 03:16:00,692 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - https://parkercfa.atlassian.net/
2019-12-06 03:16:00,695 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-12-06 03:16:00,696 [taskScheduler-1] INFO  c.c.d.collector.FeatureCollectorTask - JIRA Collector is set to work in Board mode
2019-12-06 03:16:00,697 [taskScheduler-1] INFO  c.c.d.collector.FeatureCollectorTask - Hours since last run = 16. Collector is about to refresh Team/Board information
2019-12-06 03:16:00,812 [taskScheduler-1] INFO  c.c.dashboard.client.RestClient - makeRestCall op=GET url=https://parkercfa.atlassian.net/rest/agile/1.0/board?startAt=0 status=401 duration=113
2019-12-06 03:16:00,814 [taskScheduler-1] ERROR c.c.d.collector.DefaultJiraClient - Error in calling JIRA API: https://parkercfa.atlassian.net/rest/agile/1.0/board?startAt=0
2019-12-06 03:16:00,823 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Board Data Collected. Added  0        0s
2019-12-06 03:16:00,925 [taskScheduler-1] INFO  c.c.dashboard.client.RestClient - makeRestCall op=GET url=https://parkercfa.atlassian.net/rest/api/2/project status=200 duration=56
2019-12-06 03:16:00,936 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Project Data Collected  0        0s
2019-12-06 03:16:00,992 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Board Issues Refreshed           0s
2019-12-06 03:16:01,021 [taskScheduler-1] INFO  c.c.d.collector.FeatureCollectorTask - Collected 0 teams and 0 projects
2019-12-06 03:16:01,045 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Finished                         0s

**Comment by Sbrenthughes** [comment]
You need to add in the credentials to the properties file. I see a 401 in the logs. 

```
# For basic authentication, requires username:password as string in base64
# This command will make this for you:  echo -n username:password | base64

feature.jiraCredentials=dXNlcm5hbWU6cGFzc3dvcmQ=
```

**Comment by Hemila-S** [comment]
We have tried again without giving the credential it's running fine without
errors but not collecting the data.

We also tried by giving credential it is throwing 401 error - while
makeRestcall to issuetype

**Comment by Hemila-S** [comment]
2019-12-06 10:54:00,002 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2019-12-06 10:54:00,202 [taskScheduler-1] INFO  c.c.dashboard.client.RestClient - makeRestCall op=GET url=https://parkercfa.atlassian.net/rest/api/2/issuetype status=401 duration=194
2019-12-06 10:54:00,203 [taskScheduler-1] ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
org.springframework.web.client.HttpClientErrorException: 401 null
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:557) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:475) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at com.capitalone.dashboard.client.RestClient.makeRestCallGet(RestClient.java:154) ~[core-3.1.9.jar!/:3.1.9]
        at com.capitalone.dashboard.collector.DefaultJiraClient.makeRestCall(DefaultJiraClient.java:832) ~[jira-feature-collector.jar!/:3.1.2-SNAPSHOT]
        at com.capitalone.dashboard.collector.DefaultJiraClient.getJiraIssueTypeIds(DefaultJiraClient.java:303) ~[jira-feature-collector.jar!/:3.1.2-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.getCollector(FeatureCollectorTask.java:95) ~[jira-feature-collector.jar!/:3.1.2-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.getCollector(FeatureCollectorTask.java:48) ~[jira-feature-collector.jar!/:3.1.2-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:52) ~[core-3.1.9.jar!/:3.1.2-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_231]
        at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_231]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.8.0_231]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_231]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_231]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_231]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_231]

**Comment by Sbrenthughes** [comment]
Can you try making that api call in postman with your credentials?

**Comment by Hemila-S** [comment]
We are getting same 401 error
![401error](https://user-images.githubusercontent.com/25076461/70416923-1ddc0e00-1a2e-11ea-9c21-a4d3d3eb6f93.PNG)
We don't have admin access for this credential

**Comment by Sbrenthughes** [comment]
Unless your company restricted the Jira api further than normal anyone who can login should have access to the apis.

` echo -n username:password | base64` - this is how you generated the token?

**Comment by Hemila-S** [comment]
Yes i have added the credentials in the Authorization tab using Basic Auth

**Comment by Hemila-S** [comment]
Will check with other credentials and check whether we have access for the apis

**Comment by Hemila-S** [comment]
Yes we have generated by the above mentioned format only

**Comment by Sbrenthughes** [comment]
Did you check to see if you had access to other apis?

**Comment by Hemila-S** [comment]
For all the apis its throwing 401 error in Postman . But we are able to see the result in browser
![image](https://user-images.githubusercontent.com/25076461/70603408-7fce7c00-1bc4-11ea-8dfc-4fb2f7720dbe.png)

**Comment by Sbrenthughes** [comment]
From your postman screenshot I don't see the Authorization tab.

**Comment by Hemila-S** [comment]
![image](https://user-images.githubusercontent.com/25076461/70693063-a7881780-1c8a-11ea-848b-51fee9764f7e.png)

**Comment by Sbrenthughes** [comment]
Can you work with your jira team to resolve this issue first? If you can't call the api this way you will not be able to use the collector.

**Comment by Hemila-S** [comment]
Okay sure.. .
If we want to call the api do we need admin access for that?
Is that necessary?

**Comment by Sbrenthughes** [comment]
That is up to the team that manages your jira instance.

**Comment by Sbrenthughes** [comment]
If you can call it from the browser your should have access to call it from postman.

**Comment by Hemila-S** [comment]
Okay will check with the jira team
