### ISSUE TITLE
 Failed to collect jira information java.lang.IllegalArgumentException: Not enough variable values available to expand 

### ISSUE THREAD

**Issue by labrlearning** [hygieia/hygieia-feature-jira-collector#61]
I have a situation where I have the collector starting to pull data from boards.  It gets to 7 out of 35 and I get an exception:

```
[taskScheduler-1] ERROR c.c.d.collector.FeatureCollectorTask - Failed to collect jira information
java.lang.IllegalArgumentException: Not enough variable values available to expand 'summaryBean=com.atlassian.jira.plugin.devstatus.rest.SummaryBean@efce3f1[summary=,errors=[],configErrors=[]], devSummaryJson='
        at org.springframework.web.util.UriComponents$VarArgsTemplateVariables.getValue(UriComponents.java:329)
        at org.springframework.web.util.UriComponents.expandUriComponent(UriComponents.java:232)
        at org.springframework.web.util.HierarchicalUriComponents$FullPathComponent.expand(HierarchicalUriComponents.java:690)
        at org.springframework.web.util.HierarchicalUriComponents.expandInternal(HierarchicalUriComponents.java:330)
        at org.springframework.web.util.HierarchicalUriComponents.expandInternal(HierarchicalUriComponents.java:48)
        at org.springframework.web.util.UriComponents.expand(UriComponents.java:165)
```

so I get no data back.  Not sure what I should be looking at to fix this issue.

**Comment by labrlearning** [comment]
Some additional information - the first run collects all of the boards, but when it cycles back on the next run to get issues, this error happens.  there is no data in the database under the feature folder. there are no errors prior to this by the collector.
