### ISSUE TITLE
Failing to collect Jira sprint data. Array of sprint data (also as array) is being pulled from Jira cloud but is attempting to cast into string and parse data.

### ISSUE THREAD

**Issue by IsaacMcIntyre** [hygieia/hygieia-feature-jira-collector#62]
```
2021-05-20 10:17:09,145 [taskScheduler-1] ERROR c.c.d.collector.FeatureCollectorTask - Failed to collect jira information
java.lang.ClassCastException: class org.json.simple.JSONObject cannot be cast to class java.lang.String (org.json.simple.JSONObject is in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @50040f0c; java.lang.String is in module java.base of loader 'bootstrap')
        at com.capitalone.dashboard.collector.SprintFormatter.parseSprint(SprintFormatter.java:36)
        at com.capitalone.dashboard.collector.DefaultJiraClient.getSprint(DefaultJiraClient.java:608)
        at com.capitalone.dashboard.collector.DefaultJiraClient.getFeature(DefaultJiraClient.java:530)
        at com.capitalone.dashboard.collector.DefaultJiraClient.lambda$getFeaturesFromQueryURL$1(DefaultJiraClient.java:403)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
        at com.capitalone.dashboard.collector.DefaultJiraClient.getFeaturesFromQueryURL(DefaultJiraClient.java:389)
        at com.capitalone.dashboard.collector.DefaultJiraClient.getIssues(DefaultJiraClient.java:265)
        at com.capitalone.dashboard.collector.FeatureCollectorTask.lambda$updateStoryInformation$7(FeatureCollectorTask.java:279)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
        at com.capitalone.dashboard.collector.FeatureCollectorTask.updateStoryInformation(FeatureCollectorTask.java:276)
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:162)
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:50)
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:69)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:835)
```

While the spring data response is coming across as a JSON object:

```
"goal" -> "Goal info."
"endDate" -> "2021-03-03T18:35:00.000Z"
"name" -> "Sprint"
"boardId" -> {Long@8455} 798
"id" -> {Long@8457} 2410
"state" -> "closed"
"startDate" -> "2021-02-18T10:35:43.348Z"
"completeDate" -> "2021-03-04T09:04:33.861Z"

```

I'm not sure to why the SpringFormatter.parseSprint is trying to handle the data like this. Using latest version of this collector with Jira Cloud.

**Comment by justindgarrett** [comment]
I'm having the same issue. My initial speculation is maybe the Jira API spec has changed since the last time this was worked on? I've been trying to rework my own fork of it, to get it up and working, as this is the last collector I need to get working for my orgs Hygieia use.
